### PR TITLE
Update dependencies for babel-eslint and broccoli-lint-eslint.

### LINKED ISSUE #4: Support ESLint 2
There are a number of things that have changed with ESLint 2, including a number of rule definitions. For one such example, I'm running into a missing definition of the `keyword-spacing` rule, which seems to have replaced a couple other similar definitions in ESLint 1.

### LINKED ISSUE #5: Block node dependencies
Hi!
Recently, broccoli-lint-eslint started to require node version that supports ES6, see https://github.com/jonathanKingston/broccoli-lint-eslint/pull/11.

Because of that our build process started to fail (we still have to use node 0.12.x) and we had to create a fork with locked version of broccoli-lint-eslint, see https://github.com/Wikia/ember-cli-qunit-eslint/commit/67a641d04cb23cb09bc311fc1e4f0fb4358c1336.

It would be nice if you could block versions in your repo so we can use it again. Thanks!

### PR DESCRIPTION
**Pull request by chriskrycho**
Resolves #4, resolves #5.

### CODE REVIEW

**Comment by martndemus** [comment]
Thanks!

**Comment by chriskrycho** [comment]
My pleasure!

**Comment by chriskrycho** [comment]
@martndemus, ETA for a bump to the npm version? Since this bumps the underlying ESLint dependency, it might be worth a full major bump (the underlying API has changed).

**Comment by martndemus** [comment]
Yes, sorry GH was down, I have published 2.0.0 just now!

**Comment by chriskrycho** [comment]
Heh, I saw that GitHub went down about a minute after I posted that. No worries, and no intent to be pushy; just wanted to confirm. Much obliged, and thanks for the quick responses!

**Comment by chriskrycho** [comment]
Quick follow-up: looks like the `npm publish` step got missed/failed/etc.; it's not showing up on npm yet. Thanks again!

**Pull request merged**
